version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:    
      - ./postgresdb/dbScriptInitialSetup.sql:/docker-entrypoint-initdb.d/create_tables.sql

  api:
    container_name: backend-api
    build:
      context: ./../backend
    image: golf-tee-time-schedule-api
    depends_on:
      - db
    ports:
      - 5100:5100
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
    links:
      - db