version: '3.8'
services:
  db:
    container_name: golf_tee_time_db
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:    
      - ./postgresdb/dbScriptInitialSetup.sql:/docker-entrypoint-initdb.d/create_tables.sql
      
  api:
    container_name: golf_tee_time_backend
    build:
      context: ./../backend
      dockerfile: ./../backend/Dockerfile
    image: img_golf_tee_time_backend
    depends_on:
      - db
    ports:
      - 5100:5100
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
    links:
      - db
   
  frontend:
    container_name: golf_tee_time_frontend
    build:
      context:  ./../frontend
      dockerfile: ./../frontend/Dockerfile
    restart: always
    image: img_golf_tee_time_frontend 
    ports:
      - "3000:3000"
    volumes:
      - ./../frontend:/app
      - ./../frontend/node_modules:/app/node_modules
    deploy:
      mode: replicated
      replicas: 1
 
volumes:
  db:
    driver: local